/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PracticeRouteRouteImport } from './routes/practice/route'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as PracticeReviewRouteImport } from './routes/practice/review'
import { Route as PracticeQuestionRouteImport } from './routes/practice/question'
import { Route as MainCollectionsCollectionIdRouteRouteImport } from './routes/_main/collections/$collectionId/route'
import { Route as MainCollectionsCollectionIdQuestionsIndexRouteImport } from './routes/_main/collections/$collectionId/questions/index'
import { Route as MainCollectionsCollectionIdPracticesIndexRouteImport } from './routes/_main/collections/$collectionId/practices/index'
import { Route as MainCollectionsCollectionIdQuestionsNewRouteImport } from './routes/_main/collections/$collectionId/questions/new'
import { Route as MainCollectionsCollectionIdPracticesPracticeIdRouteImport } from './routes/_main/collections/$collectionId/practices/$practiceId'
import { Route as MainCollectionsCollectionIdQuestionsQuestionIdUpdateRouteImport } from './routes/_main/collections/$collectionId/questions/$questionId.update'
import { Route as BlankCollectionsCollectionIdPracticesPracticeIdPracticeIndexRouteImport } from './routes/_blank/collections/$collectionId/practices/$practiceId/practice/index'
import { Route as BlankCollectionsCollectionIdPracticesPracticeIdPracticeReviewRouteImport } from './routes/_blank/collections/$collectionId/practices/$practiceId/practice/review'

const PracticeRouteRoute = PracticeRouteRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const PracticeReviewRoute = PracticeReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => PracticeRouteRoute,
} as any)
const PracticeQuestionRoute = PracticeQuestionRouteImport.update({
  id: '/question',
  path: '/question',
  getParentRoute: () => PracticeRouteRoute,
} as any)
const MainCollectionsCollectionIdRouteRoute =
  MainCollectionsCollectionIdRouteRouteImport.update({
    id: '/collections/$collectionId',
    path: '/collections/$collectionId',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainCollectionsCollectionIdQuestionsIndexRoute =
  MainCollectionsCollectionIdQuestionsIndexRouteImport.update({
    id: '/questions/',
    path: '/questions/',
    getParentRoute: () => MainCollectionsCollectionIdRouteRoute,
  } as any)
const MainCollectionsCollectionIdPracticesIndexRoute =
  MainCollectionsCollectionIdPracticesIndexRouteImport.update({
    id: '/practices/',
    path: '/practices/',
    getParentRoute: () => MainCollectionsCollectionIdRouteRoute,
  } as any)
const MainCollectionsCollectionIdQuestionsNewRoute =
  MainCollectionsCollectionIdQuestionsNewRouteImport.update({
    id: '/questions/new',
    path: '/questions/new',
    getParentRoute: () => MainCollectionsCollectionIdRouteRoute,
  } as any)
const MainCollectionsCollectionIdPracticesPracticeIdRoute =
  MainCollectionsCollectionIdPracticesPracticeIdRouteImport.update({
    id: '/practices/$practiceId',
    path: '/practices/$practiceId',
    getParentRoute: () => MainCollectionsCollectionIdRouteRoute,
  } as any)
const MainCollectionsCollectionIdQuestionsQuestionIdUpdateRoute =
  MainCollectionsCollectionIdQuestionsQuestionIdUpdateRouteImport.update({
    id: '/questions/$questionId/update',
    path: '/questions/$questionId/update',
    getParentRoute: () => MainCollectionsCollectionIdRouteRoute,
  } as any)
const BlankCollectionsCollectionIdPracticesPracticeIdPracticeIndexRoute =
  BlankCollectionsCollectionIdPracticesPracticeIdPracticeIndexRouteImport.update(
    {
      id: '/_blank/collections/$collectionId/practices/$practiceId/practice/',
      path: '/collections/$collectionId/practices/$practiceId/practice/',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const BlankCollectionsCollectionIdPracticesPracticeIdPracticeReviewRoute =
  BlankCollectionsCollectionIdPracticesPracticeIdPracticeReviewRouteImport.update(
    {
      id: '/_blank/collections/$collectionId/practices/$practiceId/practice/review',
      path: '/collections/$collectionId/practices/$practiceId/practice/review',
      getParentRoute: () => rootRouteImport,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/practice': typeof PracticeRouteRouteWithChildren
  '/practice/question': typeof PracticeQuestionRoute
  '/practice/review': typeof PracticeReviewRoute
  '/': typeof MainIndexRoute
  '/collections/$collectionId': typeof MainCollectionsCollectionIdRouteRouteWithChildren
  '/collections/$collectionId/practices/$practiceId': typeof MainCollectionsCollectionIdPracticesPracticeIdRoute
  '/collections/$collectionId/questions/new': typeof MainCollectionsCollectionIdQuestionsNewRoute
  '/collections/$collectionId/practices': typeof MainCollectionsCollectionIdPracticesIndexRoute
  '/collections/$collectionId/questions': typeof MainCollectionsCollectionIdQuestionsIndexRoute
  '/collections/$collectionId/questions/$questionId/update': typeof MainCollectionsCollectionIdQuestionsQuestionIdUpdateRoute
  '/collections/$collectionId/practices/$practiceId/practice/review': typeof BlankCollectionsCollectionIdPracticesPracticeIdPracticeReviewRoute
  '/collections/$collectionId/practices/$practiceId/practice': typeof BlankCollectionsCollectionIdPracticesPracticeIdPracticeIndexRoute
}
export interface FileRoutesByTo {
  '/practice': typeof PracticeRouteRouteWithChildren
  '/practice/question': typeof PracticeQuestionRoute
  '/practice/review': typeof PracticeReviewRoute
  '/': typeof MainIndexRoute
  '/collections/$collectionId': typeof MainCollectionsCollectionIdRouteRouteWithChildren
  '/collections/$collectionId/practices/$practiceId': typeof MainCollectionsCollectionIdPracticesPracticeIdRoute
  '/collections/$collectionId/questions/new': typeof MainCollectionsCollectionIdQuestionsNewRoute
  '/collections/$collectionId/practices': typeof MainCollectionsCollectionIdPracticesIndexRoute
  '/collections/$collectionId/questions': typeof MainCollectionsCollectionIdQuestionsIndexRoute
  '/collections/$collectionId/questions/$questionId/update': typeof MainCollectionsCollectionIdQuestionsQuestionIdUpdateRoute
  '/collections/$collectionId/practices/$practiceId/practice/review': typeof BlankCollectionsCollectionIdPracticesPracticeIdPracticeReviewRoute
  '/collections/$collectionId/practices/$practiceId/practice': typeof BlankCollectionsCollectionIdPracticesPracticeIdPracticeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/practice': typeof PracticeRouteRouteWithChildren
  '/practice/question': typeof PracticeQuestionRoute
  '/practice/review': typeof PracticeReviewRoute
  '/_main/': typeof MainIndexRoute
  '/_main/collections/$collectionId': typeof MainCollectionsCollectionIdRouteRouteWithChildren
  '/_main/collections/$collectionId/practices/$practiceId': typeof MainCollectionsCollectionIdPracticesPracticeIdRoute
  '/_main/collections/$collectionId/questions/new': typeof MainCollectionsCollectionIdQuestionsNewRoute
  '/_main/collections/$collectionId/practices/': typeof MainCollectionsCollectionIdPracticesIndexRoute
  '/_main/collections/$collectionId/questions/': typeof MainCollectionsCollectionIdQuestionsIndexRoute
  '/_main/collections/$collectionId/questions/$questionId/update': typeof MainCollectionsCollectionIdQuestionsQuestionIdUpdateRoute
  '/_blank/collections/$collectionId/practices/$practiceId/practice/review': typeof BlankCollectionsCollectionIdPracticesPracticeIdPracticeReviewRoute
  '/_blank/collections/$collectionId/practices/$practiceId/practice/': typeof BlankCollectionsCollectionIdPracticesPracticeIdPracticeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/practice'
    | '/practice/question'
    | '/practice/review'
    | '/'
    | '/collections/$collectionId'
    | '/collections/$collectionId/practices/$practiceId'
    | '/collections/$collectionId/questions/new'
    | '/collections/$collectionId/practices'
    | '/collections/$collectionId/questions'
    | '/collections/$collectionId/questions/$questionId/update'
    | '/collections/$collectionId/practices/$practiceId/practice/review'
    | '/collections/$collectionId/practices/$practiceId/practice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/practice'
    | '/practice/question'
    | '/practice/review'
    | '/'
    | '/collections/$collectionId'
    | '/collections/$collectionId/practices/$practiceId'
    | '/collections/$collectionId/questions/new'
    | '/collections/$collectionId/practices'
    | '/collections/$collectionId/questions'
    | '/collections/$collectionId/questions/$questionId/update'
    | '/collections/$collectionId/practices/$practiceId/practice/review'
    | '/collections/$collectionId/practices/$practiceId/practice'
  id:
    | '__root__'
    | '/_main'
    | '/practice'
    | '/practice/question'
    | '/practice/review'
    | '/_main/'
    | '/_main/collections/$collectionId'
    | '/_main/collections/$collectionId/practices/$practiceId'
    | '/_main/collections/$collectionId/questions/new'
    | '/_main/collections/$collectionId/practices/'
    | '/_main/collections/$collectionId/questions/'
    | '/_main/collections/$collectionId/questions/$questionId/update'
    | '/_blank/collections/$collectionId/practices/$practiceId/practice/review'
    | '/_blank/collections/$collectionId/practices/$practiceId/practice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  PracticeRouteRoute: typeof PracticeRouteRouteWithChildren
  BlankCollectionsCollectionIdPracticesPracticeIdPracticeReviewRoute: typeof BlankCollectionsCollectionIdPracticesPracticeIdPracticeReviewRoute
  BlankCollectionsCollectionIdPracticesPracticeIdPracticeIndexRoute: typeof BlankCollectionsCollectionIdPracticesPracticeIdPracticeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/practice/review': {
      id: '/practice/review'
      path: '/review'
      fullPath: '/practice/review'
      preLoaderRoute: typeof PracticeReviewRouteImport
      parentRoute: typeof PracticeRouteRoute
    }
    '/practice/question': {
      id: '/practice/question'
      path: '/question'
      fullPath: '/practice/question'
      preLoaderRoute: typeof PracticeQuestionRouteImport
      parentRoute: typeof PracticeRouteRoute
    }
    '/_main/collections/$collectionId': {
      id: '/_main/collections/$collectionId'
      path: '/collections/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof MainCollectionsCollectionIdRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/collections/$collectionId/questions/': {
      id: '/_main/collections/$collectionId/questions/'
      path: '/questions'
      fullPath: '/collections/$collectionId/questions'
      preLoaderRoute: typeof MainCollectionsCollectionIdQuestionsIndexRouteImport
      parentRoute: typeof MainCollectionsCollectionIdRouteRoute
    }
    '/_main/collections/$collectionId/practices/': {
      id: '/_main/collections/$collectionId/practices/'
      path: '/practices'
      fullPath: '/collections/$collectionId/practices'
      preLoaderRoute: typeof MainCollectionsCollectionIdPracticesIndexRouteImport
      parentRoute: typeof MainCollectionsCollectionIdRouteRoute
    }
    '/_main/collections/$collectionId/questions/new': {
      id: '/_main/collections/$collectionId/questions/new'
      path: '/questions/new'
      fullPath: '/collections/$collectionId/questions/new'
      preLoaderRoute: typeof MainCollectionsCollectionIdQuestionsNewRouteImport
      parentRoute: typeof MainCollectionsCollectionIdRouteRoute
    }
    '/_main/collections/$collectionId/practices/$practiceId': {
      id: '/_main/collections/$collectionId/practices/$practiceId'
      path: '/practices/$practiceId'
      fullPath: '/collections/$collectionId/practices/$practiceId'
      preLoaderRoute: typeof MainCollectionsCollectionIdPracticesPracticeIdRouteImport
      parentRoute: typeof MainCollectionsCollectionIdRouteRoute
    }
    '/_main/collections/$collectionId/questions/$questionId/update': {
      id: '/_main/collections/$collectionId/questions/$questionId/update'
      path: '/questions/$questionId/update'
      fullPath: '/collections/$collectionId/questions/$questionId/update'
      preLoaderRoute: typeof MainCollectionsCollectionIdQuestionsQuestionIdUpdateRouteImport
      parentRoute: typeof MainCollectionsCollectionIdRouteRoute
    }
    '/_blank/collections/$collectionId/practices/$practiceId/practice/': {
      id: '/_blank/collections/$collectionId/practices/$practiceId/practice/'
      path: '/collections/$collectionId/practices/$practiceId/practice'
      fullPath: '/collections/$collectionId/practices/$practiceId/practice'
      preLoaderRoute: typeof BlankCollectionsCollectionIdPracticesPracticeIdPracticeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_blank/collections/$collectionId/practices/$practiceId/practice/review': {
      id: '/_blank/collections/$collectionId/practices/$practiceId/practice/review'
      path: '/collections/$collectionId/practices/$practiceId/practice/review'
      fullPath: '/collections/$collectionId/practices/$practiceId/practice/review'
      preLoaderRoute: typeof BlankCollectionsCollectionIdPracticesPracticeIdPracticeReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MainCollectionsCollectionIdRouteRouteChildren {
  MainCollectionsCollectionIdPracticesPracticeIdRoute: typeof MainCollectionsCollectionIdPracticesPracticeIdRoute
  MainCollectionsCollectionIdQuestionsNewRoute: typeof MainCollectionsCollectionIdQuestionsNewRoute
  MainCollectionsCollectionIdPracticesIndexRoute: typeof MainCollectionsCollectionIdPracticesIndexRoute
  MainCollectionsCollectionIdQuestionsIndexRoute: typeof MainCollectionsCollectionIdQuestionsIndexRoute
  MainCollectionsCollectionIdQuestionsQuestionIdUpdateRoute: typeof MainCollectionsCollectionIdQuestionsQuestionIdUpdateRoute
}

const MainCollectionsCollectionIdRouteRouteChildren: MainCollectionsCollectionIdRouteRouteChildren =
  {
    MainCollectionsCollectionIdPracticesPracticeIdRoute:
      MainCollectionsCollectionIdPracticesPracticeIdRoute,
    MainCollectionsCollectionIdQuestionsNewRoute:
      MainCollectionsCollectionIdQuestionsNewRoute,
    MainCollectionsCollectionIdPracticesIndexRoute:
      MainCollectionsCollectionIdPracticesIndexRoute,
    MainCollectionsCollectionIdQuestionsIndexRoute:
      MainCollectionsCollectionIdQuestionsIndexRoute,
    MainCollectionsCollectionIdQuestionsQuestionIdUpdateRoute:
      MainCollectionsCollectionIdQuestionsQuestionIdUpdateRoute,
  }

const MainCollectionsCollectionIdRouteRouteWithChildren =
  MainCollectionsCollectionIdRouteRoute._addFileChildren(
    MainCollectionsCollectionIdRouteRouteChildren,
  )

interface MainRouteRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
  MainCollectionsCollectionIdRouteRoute: typeof MainCollectionsCollectionIdRouteRouteWithChildren
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainIndexRoute: MainIndexRoute,
  MainCollectionsCollectionIdRouteRoute:
    MainCollectionsCollectionIdRouteRouteWithChildren,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface PracticeRouteRouteChildren {
  PracticeQuestionRoute: typeof PracticeQuestionRoute
  PracticeReviewRoute: typeof PracticeReviewRoute
}

const PracticeRouteRouteChildren: PracticeRouteRouteChildren = {
  PracticeQuestionRoute: PracticeQuestionRoute,
  PracticeReviewRoute: PracticeReviewRoute,
}

const PracticeRouteRouteWithChildren = PracticeRouteRoute._addFileChildren(
  PracticeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  PracticeRouteRoute: PracticeRouteRouteWithChildren,
  BlankCollectionsCollectionIdPracticesPracticeIdPracticeReviewRoute:
    BlankCollectionsCollectionIdPracticesPracticeIdPracticeReviewRoute,
  BlankCollectionsCollectionIdPracticesPracticeIdPracticeIndexRoute:
    BlankCollectionsCollectionIdPracticesPracticeIdPracticeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
