/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsCollectionIdIndexRouteImport } from './routes/collections/$collectionId/index'
import { Route as CollectionsCollectionIdQuestionsNewRouteImport } from './routes/collections/$collectionId/questions/new'
import { Route as CollectionsCollectionIdQuestionsQuestionIdUpdateRouteImport } from './routes/collections/$collectionId/questions/$questionId.update'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCollectionIdIndexRoute =
  CollectionsCollectionIdIndexRouteImport.update({
    id: '/collections/$collectionId/',
    path: '/collections/$collectionId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CollectionsCollectionIdQuestionsNewRoute =
  CollectionsCollectionIdQuestionsNewRouteImport.update({
    id: '/collections/$collectionId/questions/new',
    path: '/collections/$collectionId/questions/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const CollectionsCollectionIdQuestionsQuestionIdUpdateRoute =
  CollectionsCollectionIdQuestionsQuestionIdUpdateRouteImport.update({
    id: '/collections/$collectionId/questions/$questionId/update',
    path: '/collections/$collectionId/questions/$questionId/update',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdIndexRoute
  '/collections/$collectionId/questions/new': typeof CollectionsCollectionIdQuestionsNewRoute
  '/collections/$collectionId/questions/$questionId/update': typeof CollectionsCollectionIdQuestionsQuestionIdUpdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdIndexRoute
  '/collections/$collectionId/questions/new': typeof CollectionsCollectionIdQuestionsNewRoute
  '/collections/$collectionId/questions/$questionId/update': typeof CollectionsCollectionIdQuestionsQuestionIdUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections/$collectionId/': typeof CollectionsCollectionIdIndexRoute
  '/collections/$collectionId/questions/new': typeof CollectionsCollectionIdQuestionsNewRoute
  '/collections/$collectionId/questions/$questionId/update': typeof CollectionsCollectionIdQuestionsQuestionIdUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections/$collectionId'
    | '/collections/$collectionId/questions/new'
    | '/collections/$collectionId/questions/$questionId/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections/$collectionId'
    | '/collections/$collectionId/questions/new'
    | '/collections/$collectionId/questions/$questionId/update'
  id:
    | '__root__'
    | '/'
    | '/collections/$collectionId/'
    | '/collections/$collectionId/questions/new'
    | '/collections/$collectionId/questions/$questionId/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsCollectionIdIndexRoute: typeof CollectionsCollectionIdIndexRoute
  CollectionsCollectionIdQuestionsNewRoute: typeof CollectionsCollectionIdQuestionsNewRoute
  CollectionsCollectionIdQuestionsQuestionIdUpdateRoute: typeof CollectionsCollectionIdQuestionsQuestionIdUpdateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collectionId/': {
      id: '/collections/$collectionId/'
      path: '/collections/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof CollectionsCollectionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collectionId/questions/new': {
      id: '/collections/$collectionId/questions/new'
      path: '/collections/$collectionId/questions/new'
      fullPath: '/collections/$collectionId/questions/new'
      preLoaderRoute: typeof CollectionsCollectionIdQuestionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collectionId/questions/$questionId/update': {
      id: '/collections/$collectionId/questions/$questionId/update'
      path: '/collections/$collectionId/questions/$questionId/update'
      fullPath: '/collections/$collectionId/questions/$questionId/update'
      preLoaderRoute: typeof CollectionsCollectionIdQuestionsQuestionIdUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsCollectionIdIndexRoute: CollectionsCollectionIdIndexRoute,
  CollectionsCollectionIdQuestionsNewRoute:
    CollectionsCollectionIdQuestionsNewRoute,
  CollectionsCollectionIdQuestionsQuestionIdUpdateRoute:
    CollectionsCollectionIdQuestionsQuestionIdUpdateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
