/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PracticeRouteRouteImport } from './routes/practice/route'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticeReviewRouteImport } from './routes/practice/review'
import { Route as PracticeQuestionRouteImport } from './routes/practice/question'
import { Route as MainCollectionsCollectionIdRouteRouteImport } from './routes/_main/collections/$collectionId/route'
import { Route as MainCollectionsCollectionIdPracticesRouteImport } from './routes/_main/collections/$collectionId/practices'
import { Route as MainCollectionsCollectionIdQuestionsIndexRouteImport } from './routes/_main/collections/$collectionId/questions/index'
import { Route as MainCollectionsCollectionIdQuestionsNewRouteImport } from './routes/_main/collections/$collectionId/questions/new'
import { Route as MainCollectionsCollectionIdQuestionsQuestionIdUpdateRouteImport } from './routes/_main/collections/$collectionId/questions/$questionId.update'

const PracticeRouteRoute = PracticeRouteRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeReviewRoute = PracticeReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => PracticeRouteRoute,
} as any)
const PracticeQuestionRoute = PracticeQuestionRouteImport.update({
  id: '/question',
  path: '/question',
  getParentRoute: () => PracticeRouteRoute,
} as any)
const MainCollectionsCollectionIdRouteRoute =
  MainCollectionsCollectionIdRouteRouteImport.update({
    id: '/collections/$collectionId',
    path: '/collections/$collectionId',
    getParentRoute: () => MainRouteRoute,
  } as any)
const MainCollectionsCollectionIdPracticesRoute =
  MainCollectionsCollectionIdPracticesRouteImport.update({
    id: '/practices',
    path: '/practices',
    getParentRoute: () => MainCollectionsCollectionIdRouteRoute,
  } as any)
const MainCollectionsCollectionIdQuestionsIndexRoute =
  MainCollectionsCollectionIdQuestionsIndexRouteImport.update({
    id: '/questions/',
    path: '/questions/',
    getParentRoute: () => MainCollectionsCollectionIdRouteRoute,
  } as any)
const MainCollectionsCollectionIdQuestionsNewRoute =
  MainCollectionsCollectionIdQuestionsNewRouteImport.update({
    id: '/questions/new',
    path: '/questions/new',
    getParentRoute: () => MainCollectionsCollectionIdRouteRoute,
  } as any)
const MainCollectionsCollectionIdQuestionsQuestionIdUpdateRoute =
  MainCollectionsCollectionIdQuestionsQuestionIdUpdateRouteImport.update({
    id: '/questions/$questionId/update',
    path: '/questions/$questionId/update',
    getParentRoute: () => MainCollectionsCollectionIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/practice': typeof PracticeRouteRouteWithChildren
  '/practice/question': typeof PracticeQuestionRoute
  '/practice/review': typeof PracticeReviewRoute
  '/collections/$collectionId': typeof MainCollectionsCollectionIdRouteRouteWithChildren
  '/collections/$collectionId/practices': typeof MainCollectionsCollectionIdPracticesRoute
  '/collections/$collectionId/questions/new': typeof MainCollectionsCollectionIdQuestionsNewRoute
  '/collections/$collectionId/questions': typeof MainCollectionsCollectionIdQuestionsIndexRoute
  '/collections/$collectionId/questions/$questionId/update': typeof MainCollectionsCollectionIdQuestionsQuestionIdUpdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/practice': typeof PracticeRouteRouteWithChildren
  '/practice/question': typeof PracticeQuestionRoute
  '/practice/review': typeof PracticeReviewRoute
  '/collections/$collectionId': typeof MainCollectionsCollectionIdRouteRouteWithChildren
  '/collections/$collectionId/practices': typeof MainCollectionsCollectionIdPracticesRoute
  '/collections/$collectionId/questions/new': typeof MainCollectionsCollectionIdQuestionsNewRoute
  '/collections/$collectionId/questions': typeof MainCollectionsCollectionIdQuestionsIndexRoute
  '/collections/$collectionId/questions/$questionId/update': typeof MainCollectionsCollectionIdQuestionsQuestionIdUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_main': typeof MainRouteRouteWithChildren
  '/practice': typeof PracticeRouteRouteWithChildren
  '/practice/question': typeof PracticeQuestionRoute
  '/practice/review': typeof PracticeReviewRoute
  '/_main/collections/$collectionId': typeof MainCollectionsCollectionIdRouteRouteWithChildren
  '/_main/collections/$collectionId/practices': typeof MainCollectionsCollectionIdPracticesRoute
  '/_main/collections/$collectionId/questions/new': typeof MainCollectionsCollectionIdQuestionsNewRoute
  '/_main/collections/$collectionId/questions/': typeof MainCollectionsCollectionIdQuestionsIndexRoute
  '/_main/collections/$collectionId/questions/$questionId/update': typeof MainCollectionsCollectionIdQuestionsQuestionIdUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/practice'
    | '/practice/question'
    | '/practice/review'
    | '/collections/$collectionId'
    | '/collections/$collectionId/practices'
    | '/collections/$collectionId/questions/new'
    | '/collections/$collectionId/questions'
    | '/collections/$collectionId/questions/$questionId/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/practice'
    | '/practice/question'
    | '/practice/review'
    | '/collections/$collectionId'
    | '/collections/$collectionId/practices'
    | '/collections/$collectionId/questions/new'
    | '/collections/$collectionId/questions'
    | '/collections/$collectionId/questions/$questionId/update'
  id:
    | '__root__'
    | '/'
    | '/_main'
    | '/practice'
    | '/practice/question'
    | '/practice/review'
    | '/_main/collections/$collectionId'
    | '/_main/collections/$collectionId/practices'
    | '/_main/collections/$collectionId/questions/new'
    | '/_main/collections/$collectionId/questions/'
    | '/_main/collections/$collectionId/questions/$questionId/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRouteRoute: typeof MainRouteRouteWithChildren
  PracticeRouteRoute: typeof PracticeRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/review': {
      id: '/practice/review'
      path: '/review'
      fullPath: '/practice/review'
      preLoaderRoute: typeof PracticeReviewRouteImport
      parentRoute: typeof PracticeRouteRoute
    }
    '/practice/question': {
      id: '/practice/question'
      path: '/question'
      fullPath: '/practice/question'
      preLoaderRoute: typeof PracticeQuestionRouteImport
      parentRoute: typeof PracticeRouteRoute
    }
    '/_main/collections/$collectionId': {
      id: '/_main/collections/$collectionId'
      path: '/collections/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof MainCollectionsCollectionIdRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/collections/$collectionId/practices': {
      id: '/_main/collections/$collectionId/practices'
      path: '/practices'
      fullPath: '/collections/$collectionId/practices'
      preLoaderRoute: typeof MainCollectionsCollectionIdPracticesRouteImport
      parentRoute: typeof MainCollectionsCollectionIdRouteRoute
    }
    '/_main/collections/$collectionId/questions/': {
      id: '/_main/collections/$collectionId/questions/'
      path: '/questions'
      fullPath: '/collections/$collectionId/questions'
      preLoaderRoute: typeof MainCollectionsCollectionIdQuestionsIndexRouteImport
      parentRoute: typeof MainCollectionsCollectionIdRouteRoute
    }
    '/_main/collections/$collectionId/questions/new': {
      id: '/_main/collections/$collectionId/questions/new'
      path: '/questions/new'
      fullPath: '/collections/$collectionId/questions/new'
      preLoaderRoute: typeof MainCollectionsCollectionIdQuestionsNewRouteImport
      parentRoute: typeof MainCollectionsCollectionIdRouteRoute
    }
    '/_main/collections/$collectionId/questions/$questionId/update': {
      id: '/_main/collections/$collectionId/questions/$questionId/update'
      path: '/questions/$questionId/update'
      fullPath: '/collections/$collectionId/questions/$questionId/update'
      preLoaderRoute: typeof MainCollectionsCollectionIdQuestionsQuestionIdUpdateRouteImport
      parentRoute: typeof MainCollectionsCollectionIdRouteRoute
    }
  }
}

interface MainCollectionsCollectionIdRouteRouteChildren {
  MainCollectionsCollectionIdPracticesRoute: typeof MainCollectionsCollectionIdPracticesRoute
  MainCollectionsCollectionIdQuestionsNewRoute: typeof MainCollectionsCollectionIdQuestionsNewRoute
  MainCollectionsCollectionIdQuestionsIndexRoute: typeof MainCollectionsCollectionIdQuestionsIndexRoute
  MainCollectionsCollectionIdQuestionsQuestionIdUpdateRoute: typeof MainCollectionsCollectionIdQuestionsQuestionIdUpdateRoute
}

const MainCollectionsCollectionIdRouteRouteChildren: MainCollectionsCollectionIdRouteRouteChildren =
  {
    MainCollectionsCollectionIdPracticesRoute:
      MainCollectionsCollectionIdPracticesRoute,
    MainCollectionsCollectionIdQuestionsNewRoute:
      MainCollectionsCollectionIdQuestionsNewRoute,
    MainCollectionsCollectionIdQuestionsIndexRoute:
      MainCollectionsCollectionIdQuestionsIndexRoute,
    MainCollectionsCollectionIdQuestionsQuestionIdUpdateRoute:
      MainCollectionsCollectionIdQuestionsQuestionIdUpdateRoute,
  }

const MainCollectionsCollectionIdRouteRouteWithChildren =
  MainCollectionsCollectionIdRouteRoute._addFileChildren(
    MainCollectionsCollectionIdRouteRouteChildren,
  )

interface MainRouteRouteChildren {
  MainCollectionsCollectionIdRouteRoute: typeof MainCollectionsCollectionIdRouteRouteWithChildren
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainCollectionsCollectionIdRouteRoute:
    MainCollectionsCollectionIdRouteRouteWithChildren,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface PracticeRouteRouteChildren {
  PracticeQuestionRoute: typeof PracticeQuestionRoute
  PracticeReviewRoute: typeof PracticeReviewRoute
}

const PracticeRouteRouteChildren: PracticeRouteRouteChildren = {
  PracticeQuestionRoute: PracticeQuestionRoute,
  PracticeReviewRoute: PracticeReviewRoute,
}

const PracticeRouteRouteWithChildren = PracticeRouteRoute._addFileChildren(
  PracticeRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRouteRoute: MainRouteRouteWithChildren,
  PracticeRouteRoute: PracticeRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
